(()=>{
'use strict';
const DEF='135',EXCEL='4685';let lang=(localStorage.rw_lang||'pl').slice(0,2),pending=null,pin=DEF,ok=false,legacy=null;
const L={
pl:{navHome:'Start',navTools:'Narzędzia',navProjects:'My Projects',navAi:'AI Agent',tagline:'AI, automatyzacja i praktyczne narzędzia biznesowe w jednym ekosystemie.',lead:'Kalkulatory, HR, staffing, analityka i narzędzia operacyjne w jednej profesjonalnej platformie.',ctaTools:'Zobacz narzędzia',ctaProjects:'Otwórz My Projects',status:'Platforma gotowa',cap1:'Kalkulatory i modele',cap1c:'Bill rate, budżety, merit, CAO i staffing.',cap2:'HR i workforce',cap2c:'Intake, CV Match, spotkania i workflow.',cap3:'AI Assistant',cap3c:'Agent głosowy zintegrowany z platformą.',toolsK:'Narzędzia',toolsH:'Rozwiązania gotowe do pracy',toolsI:'Moduły otwierają się wewnątrz platformy z zachowaniem istniejącej logiki, PIN i języków.',catCalc:'Calculators',catRecruit:'Recruitment & Staffing',catHr:'HR & Workforce',catProjects:'My Projects',projectsK:'Chroniony obszar',projectsH:'My Projects',projectsP:'Prywatny obszar projektowy z istniejącym dostępem PIN.',projectsBtn:'Otwórz My Projects',security:'Dostęp chroniony istniejącym mechanizmem PIN.',aiH:'AI Voice Agent',aiP:'Istniejący agent głosowy działa jako integralna część platformy.',aiBtn:'Otwórz AI Agent',back:'Powrót do platformy',cancel:'Anuluj',unlock:'Odblokuj',wrong:'Nieprawidłowy kod.',footer:'Narzędzia biznesowe, AI i automatyzacja.',legal:'Legal & Privacy: zawartość platformy pozostaje własnością Rafała Wilka.',open:'Otwórz',download:'Pobierz Excel'},
en:{navHome:'Home',navTools:'Tools',navProjects:'My Projects',navAi:'AI Agent',tagline:'AI, automation and practical business tools in one ecosystem.',lead:'Calculators, HR, staffing, analytics and operational tools in one professional platform.',ctaTools:'Explore tools',ctaProjects:'Open My Projects',status:'Platform ready',cap1:'Calculators & models',cap1c:'Bill rate, budgets, merit, CAO and staffing.',cap2:'HR & workforce',cap2c:'Intake, CV Match, meetings and workflows.',cap3:'AI Assistant',cap3c:'Voice agent integrated with the platform.',toolsK:'Tools',toolsH:'Solutions ready to use',toolsI:'Modules open inside the platform while preserving existing logic, PIN access and languages.',catCalc:'Calculators',catRecruit:'Recruitment & Staffing',catHr:'HR & Workforce',catProjects:'My Projects',projectsK:'Protected area',projectsH:'My Projects',projectsP:'Private project area with the existing PIN access.',projectsBtn:'Open My Projects',security:'Protected by the existing PIN mechanism.',aiH:'AI Voice Agent',aiP:'The existing voice agent works as an integral part of the platform.',aiBtn:'Open AI Agent',back:'Back to platform',cancel:'Cancel',unlock:'Unlock',wrong:'Incorrect code.',footer:'Business tools, AI and automation.',legal:'Legal & Privacy: platform content remains the property of Rafał Wilk.',open:'Open',download:'Download Excel'},
nl:{navHome:'Start',navTools:'Tools',navProjects:'My Projects',navAi:'AI Agent',tagline:'AI, automatisering en praktische business tools in één ecosysteem.',lead:'Calculators, HR, staffing, analytics en operationele tools in één professioneel platform.',ctaTools:'Bekijk tools',ctaProjects:'Open My Projects',status:'Platform gereed',cap1:'Calculators & modellen',cap1c:'Bill rate, budgetten, merit, CAO en staffing.',cap2:'HR & workforce',cap2c:'Intake, CV Match, meetings en workflows.',cap3:'AI Assistant',cap3c:'Voice agent geïntegreerd in het platform.',toolsK:'Tools',toolsH:'Oplossingen klaar voor gebruik',toolsI:'Modules openen binnen het platform met behoud van bestaande logica, PIN-toegang en talen.',catCalc:'Calculators',catRecruit:'Recruitment & Staffing',catHr:'HR & Workforce',catProjects:'My Projects',projectsK:'Beveiligde omgeving',projectsH:'My Projects',projectsP:'Privé-projectomgeving met bestaande PIN-toegang.',projectsBtn:'Open My Projects',security:'Beveiligd met het bestaande PIN-mechanisme.',aiH:'AI Voice Agent',aiP:'De bestaande voice agent werkt als integraal onderdeel van het platform.',aiBtn:'Open AI Agent',back:'Terug naar platform',cancel:'Annuleren',unlock:'Ontgrendelen',wrong:'Onjuiste code.',footer:'Business tools, AI en automatisering.',legal:'Legal & Privacy: platforminhoud blijft eigendom van Rafał Wilk.',open:'Open',download:'Download Excel'}};
const D={
'Contract Budget Calculator':['Budżet kontraktu i kontrola kosztów.','Contract budget and cost control.','Contractbudget en kostencontrole.'],
'New Bill Rate':['Przeliczenie nowej stawki bill rate.','New bill-rate calculation.','Berekening van een nieuwe bill rate.'],
'RekenTool Master':['Główny kalkulator stawek.','Master rate calculator.','Hoofdcalculator voor tarieven.'],
'RekenTool Professional & General Staffing':['Professional i General Staffing.','Professional and General Staffing.','Professional en General Staffing.'],
'RekenTool General Staffing':['Kalkulator General Staffing.','General Staffing calculator.','General Staffing calculator.'],
'RekenTool Professional Staffing':['Kalkulator Professional Staffing.','Professional Staffing calculator.','Professional Staffing calculator.'],
'RekenTool Payroll':['Kalkulator payroll.','Payroll calculator.','Payrollcalculator.'],
'Merit Increase':['Merit increase 2026.','Merit increase 2026.','Merit increase 2026.'],
'MSD CAO Salary Check':['Sprawdzenie wynagrodzenia CAO.','CAO salary check.','CAO-salariscontrole.'],
'Merit Excel':['Arkusz kalkulacji zbiorczej.','Bulk calculation workbook.','Excel voor bulkberekeningen.'],
'Intake Call':['Wsparcie intake call.','Intake-call support.','Ondersteuning voor intake calls.'],
'CV Match':['Ocena dopasowania CV.','CV fit assessment.','Beoordeling van CV-match.'],
'Agency Overview':['Przegląd agencji.','Agency overview.','Overzicht van bureaus.'],
'Manager Meeting Register':['Rejestr spotkań z managerami.','Manager meeting register.','Register voor managermeetings.'],
'Home Office Tracker':['Śledzenie pracy z domu.','Home-office tracking.','Registratie van thuiswerk.'],
'Redukcja':['Moduł operacyjny.','Operational module.','Operationele module.'],
'My Projects':['Chroniony obszar projektów.','Protected project area.','Beveiligde projectomgeving.']};
const norm=v=>['pl','en','nl'].includes(String(v||'').slice(0,2))?String(v).slice(0,2):'pl',tr=k=>(L[lang]||L.pl)[k]||k,frames=()=>[...document.querySelectorAll('.workspace-stage iframe')];
function render(){lang=norm(lang);document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>{if(L[lang][e.dataset.i18n])e.textContent=L[lang][e.dataset.i18n]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelectorAll('[data-tool-name]').forEach(c=>{let d=c.querySelector('[data-tool-description]'),a=c.querySelector('[data-action-label]'),x=D[c.dataset.toolName];if(d&&x)d.textContent=x[{pl:0,en:1,nl:2}[lang]];if(a)a.textContent=c.dataset.download==='true'?tr('download'):tr('open')});localStorage.rw_lang=lang;localStorage.doc_lang=lang;localStorage.supplier_lang=lang;window.__rwActiveAppLang=lang;let w=document.getElementById('workspaceLang');if(w)w.textContent=lang.toUpperCase();frames().forEach(f=>sync(f));apiStatus()}
window.__rwPlatformSetLang=v=>{lang=norm(v);render()};
function parts(){return{g:document.getElementById('mc_gate'),i:document.getElementById('mc_pin'),e:document.getElementById('mc_err'),t:document.getElementById('mc_title'),p:document.getElementById('mc_text')}}
window.__rwModulePinConsume=()=>ok?(ok=false,true):false;
window.__rwRequestModulePin=(cb,title)=>{pending=cb;ok=false;pin=String(title||'').toLowerCase().includes('merit excel')?EXCEL:DEF;let x=parts();x.t.textContent=lang==='pl'?'Dostęp do modułu':lang==='nl'?'Toegang tot module':'Module access';x.p.textContent=(lang==='pl'?'Wpisz PIN, aby otworzyć: ':lang==='nl'?'Voer de PIN in voor: ':'Enter the PIN for: ')+(title||'Module');x.e.textContent='';x.i.value='';x.i.maxLength=pin.length;x.i.placeholder='•'.repeat(pin.length);x.g.style.display='flex';x.g.setAttribute('aria-hidden','false');setTimeout(()=>x.i.focus(),0)};
function unlock(){let x=parts();if(x.i.value===pin){ok=true;x.g.style.display='none';let f=pending;pending=null;x.i.value='';f&&f()}else{x.e.textContent=tr('wrong');x.i.value='';x.i.focus()}}
function closePin(){let x=parts();pending=null;ok=false;x.g.style.display='none'}
function prep(title){frames().forEach(f=>f.classList.remove('show'));document.querySelector('.viewport').classList.add('active');document.body.classList.add('app-open');document.getElementById('workspaceTitle').textContent=title||'Rafal Wilk AI';document.getElementById('workspaceLoading').hidden=false;document.title='Rafal Wilk AI — '+(title||'Module')}
function show(f,title){prep(title);f.classList.add('show');let done=()=>{document.getElementById('workspaceLoading').hidden=true;theme(f);sync(f)};if(f.contentDocument?.readyState==='complete')setTimeout(done,40);else f.addEventListener('load',done,{once:true});setTimeout(done,650)}
window.__rwSetActiveApp=title=>{if(title)document.getElementById('workspaceTitle').textContent=title};
window.__rwSaveActiveFrame=(id,title)=>{try{localStorage.rw_active_frame_state=JSON.stringify({id,title});delete localStorage.rw_active_module_idx}catch{}};
window.openApp=(id,title)=>{if(!window.__rwModulePinConsume()){window.__rwRequestModulePin(()=>window.openApp(id,title),title||id);return}let f=document.getElementById(id);if(!f)return;if(!f.src&&f.dataset.src)f.src=f.dataset.src;show(f,title)};
window.openMyCompany=()=>window.openApp('mycompany','My Projects');window.openMc=window.openMyCompany;
function closeWork(){document.body.classList.remove('app-open');document.querySelector('.viewport').classList.remove('active');frames().forEach(f=>f.classList.remove('show'));document.title='Rafal Wilk AI';try{window.__rwClearActiveModule?.();delete localStorage.rw_active_frame_state;delete localStorage.rw_active_module_idx}catch{}}
function loadLegacy(idx,title){window.__rwRequestModulePin(()=>{prep(title);if(!legacy){legacy=new Promise((res,rej)=>{let s=document.createElement('script');s.src='../assets/js/legacy-apps-bundle.js?v=20260727-cv-match-engine-4';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}legacy.then(()=>{window.loadApp?.(idx);let f=document.getElementById('appframe');setTimeout(()=>{theme(f);sync(f);document.getElementById('workspaceLoading').hidden=true},250)}).catch(()=>document.getElementById('workspaceLoading').textContent='Unable to load module.')},title)}
function merit(){window.__rwRequestModulePin(()=>{if(!window.__rwModulePinConsume())return;let a=document.createElement('a');a.href='../downloads/Merit_2026_Employee_Bulk_Calculator_350_exact.xlsx?v=authoritative-title-list-20260807-1';a.download='Merit_2026_Employee_Bulk_Calculator_350_correct_title_list_20260807.xlsx';document.body.appendChild(a);a.click();a.remove()},'Merit Excel 350')}
function sync(f){if(!f)return;try{f.contentWindow.postMessage({type:'rw:setLang',lang},'*');let w=f.contentWindow,d=f.contentDocument;if(!w||!d)return;d.documentElement.lang=lang;['__rwApplyModuleLang','__rwPlatformSetLang','setLanguage','applyLanguage','setLang','applyLang'].forEach(n=>{try{w[n]?.(lang)}catch{}})}catch{}}
function theme(f){try{let d=f.contentDocument;if(!d?.head||d.getElementById('rw-professional-theme'))return;let s=d.createElement('style');s.id='rw-professional-theme';s.textContent=`html,body{background:linear-gradient(180deg,#07111d,#050b14)!important;color:#eef6ff!important;font-family:Inter,system-ui,sans-serif!important}.card,.panel,.container>.card,.section,.box,.widget{background:rgba(10,24,41,.94)!important;border-color:rgba(118,173,246,.18)!important;color:#eef6ff!important;box-shadow:0 16px 45px rgba(0,0,0,.18)!important}h1,h2,h3,h4,strong,.title,.section-title{color:#f2f7ff!important}p,label,.muted,.sub,.subtitle,.desc{color:#9aacc1!important}input,select,textarea{background:#081523!important;color:#eef6ff!important;border-color:rgba(118,173,246,.22)!important}input:focus,select:focus,textarea:focus{border-color:#5baaff!important;box-shadow:0 0 0 3px rgba(91,170,255,.1)!important}th{background:#0b1a2c!important;color:#a9bad0!important}td{background:rgba(7,17,29,.75)!important;color:#dce8f5!important}th,td{border-color:rgba(118,173,246,.16)!important}@media(max-width:760px){table{display:block!important;overflow-x:auto!important;white-space:nowrap}}`;d.head.appendChild(s)}catch{}}
function apiStatus(){let r=document.getElementById('rwPlatformApiStatus');if(!r)return;let a=!!(localStorage.rwOpenAIKey||'').trim()&&localStorage.rwOpenAIKeyValidated==='1';r.classList.toggle('active',a);r.innerHTML=`<div class="rwStatusCard"><span class="rwDot"></span><div><div class="rwLabel">AI API</div><div class="rwValue">${a?(lang==='nl'?'Sleutel actief':lang==='en'?'Key active':'Klucz aktywny'):(lang==='nl'?'Sleutel inactief':lang==='en'?'Key inactive':'Klucz nieaktywny')}</div></div></div>`}
function bind(){document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;render()});let m=document.getElementById('mobileMenu'),n=document.getElementById('navLinks');m.onclick=()=>n.classList.toggle('open');document.querySelectorAll('#navLinks a').forEach(a=>a.onclick=()=>n.classList.remove('open'));document.querySelectorAll('[data-scroll-target]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scrollTarget)?.scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-category-target]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.categoryTarget)?.scrollIntoView({behavior:'smooth'}));document.querySelectorAll('[data-direct-frame]').forEach(b=>b.onclick=()=>window.openApp(b.dataset.directFrame,b.dataset.title));document.querySelectorAll('[data-legacy-idx]').forEach(b=>b.onclick=()=>loadLegacy(+b.dataset.legacyIdx,b.dataset.title));document.querySelectorAll('[data-my-projects]').forEach(b=>b.onclick=()=>window.openMyCompany());document.querySelectorAll('[data-download-merit]').forEach(b=>b.onclick=merit);document.querySelectorAll('[data-open-agent]').forEach(b=>b.onclick=()=>document.getElementById('rwVoiceLauncher')?.click());document.getElementById('workspaceBack').onclick=closeWork;document.getElementById('mc_ok').onclick=unlock;document.getElementById('mc_cancel').onclick=closePin;document.getElementById('mc_pin').onkeydown=e=>{if(e.key==='Enter')unlock();if(e.key==='Escape')closePin()};document.getElementById('mc_pin').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,pin.length);if(e.target.value===pin)unlock()};frames().forEach(f=>f.addEventListener('load',()=>{theme(f);sync(f)}));addEventListener('storage',apiStatus);addEventListener('scroll',()=>document.querySelector('.nav').classList.toggle('is-scrolled',scrollY>14),{passive:true});document.addEventListener('keydown',e=>{if(e.target.matches?.('input,textarea,select')||e.target.isContentEditable)return;if(e.key==='Escape'&&document.body.classList.contains('app-open'))closeWork();if(e.key.toLowerCase()==='k'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!e.shiftKey&&!e.repeat){e.preventDefault();let f=document.getElementById('msdcaosalarycheck');if(f.classList.contains('show')){f.contentWindow.postMessage({type:'msd:toggleCalculator'},'*');return}window.__rwRequestModulePin(()=>{if(!window.__rwModulePinConsume())return;if(!f.src&&f.dataset.src)f.src=f.dataset.src;show(f,'MSD CAO Salary Check');let go=()=>f.contentWindow.postMessage({type:'msd:toggleCalculator'},'*');f.addEventListener('load',()=>setTimeout(go,100),{once:true});setTimeout(go,650)},'MSD CAO Salary Check')}})}
document.addEventListener('DOMContentLoaded',()=>{bind();render()});
})();
