(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const DEFAULT_PIN='135',EXCEL_PIN='4685';
const CATEGORIES=['all','finance','staffing','workforce','private'];
const TOOLS=[
{id:'contract-budget',name:'Contract Budget Calculator',abbr:'CB',category:'finance',type:'legacy',idx:0,desc:'Contract budget and cost control.',keywords:'budget contract cost'},
{id:'new-bill-rate',name:'New Bill Rate',abbr:'BR',category:'finance',type:'legacy',idx:1,desc:'Calculate a new bill rate.',keywords:'bill rate pricing'},
{id:'rekentool-master',name:'RekenTool Master',abbr:'RM',category:'finance',type:'legacy',idx:2,desc:'Master rate and scenario calculator.',keywords:'rate scenario master'},
{id:'combined-staffing',name:'RekenTool Professional & General Staffing',abbr:'PG',category:'finance',type:'direct',src:'../modules/rekentool-combined.html',desc:'Combined professional and general staffing rates.',keywords:'professional general staffing flexcenter'},
{id:'general-staffing',name:'RekenTool General Staffing',abbr:'GS',category:'finance',type:'direct',src:'../modules/rekentool-general-staffing.html',desc:'General staffing rate calculator.',keywords:'general staffing flexcenter'},
{id:'professional-staffing',name:'RekenTool Professional Staffing',abbr:'PS',category:'finance',type:'direct',src:'../modules/rekentool-professional-staffing.html',desc:'Professional staffing rate calculator.',keywords:'professional staffing flexcenter'},
{id:'payroll',name:'RekenTool Payroll',abbr:'PR',category:'finance',type:'direct',src:'../modules/rekentool-pay-roll.html',desc:'Payroll rate calculator.',keywords:'payroll rate flexcenter'},
{id:'merit',name:'Merit Increase 2026',abbr:'MI',category:'finance',type:'legacy',idx:6,desc:'Merit increase calculation for 2026.',keywords:'merit increase salary'},
{id:'cao',name:'MSD CAO Salary Check',abbr:'CAO',category:'finance',type:'direct',src:'../modules/msd-cao-salary-check.html?v=20260817-v19-calculator-impact-v1',desc:'CAO salary check and impact calculation.',keywords:'msd cao salary check'},
{id:'merit-excel',name:'Merit Excel 350',abbr:'XL',category:'finance',type:'download',src:'../downloads/Merit_2026_Employee_Bulk_Calculator_350_exact.xlsx',desc:'Bulk merit calculation workbook.',keywords:'excel merit bulk 350',pin:EXCEL_PIN},
{id:'intake',name:'Intake Call',abbr:'IC',category:'staffing',type:'legacy',idx:3,desc:'Structured intake-call support.',keywords:'intake recruitment hiring'},
{id:'cv-match',name:'CV Match',abbr:'CV',category:'staffing',type:'legacy',idx:4,desc:'Candidate and vacancy fit assessment.',keywords:'cv resume match candidate vacancy'},
{id:'agency',name:'Agency Overview',abbr:'AO',category:'staffing',type:'legacy',idx:7,desc:'Agency and supplier overview.',keywords:'agency supplier overview'},
{id:'manager-meetings',name:'Manager Meeting Register',abbr:'MM',category:'workforce',type:'direct',src:'../modules/manager-meeting-tracker.html',desc:'Manager meeting register and follow-up.',keywords:'manager meeting register tracker'},
{id:'home-office',name:'Home Office Tracker',abbr:'HO',category:'workforce',type:'direct',src:'../modules/home-office-tracker.html',desc:'Home-office registration and tracking.',keywords:'home office remote tracker'},
{id:'reduction',name:'Redukcja',abbr:'R',category:'workforce',type:'direct',src:'../modules/redukcja.html?v=20260812-redukcja-add-week-button-1',desc:'Operational reduction workflow.',keywords:'redukcja reduction operations'},
{id:'projects',name:'My Projects',abbr:'MP',category:'private',type:'direct',src:'../modules/my-company.html',desc:'Protected private project workspace.',keywords:'projects private my company'}
];
const I18N={
pl:{navAbout:'Platforma',navAi:'AI Assistant',openTools:'Narzędzia',eyebrow:'BUSINESS OPERATING LAYER',headline:'Narzędzia do pracy.<br><span>Bez bałaganu.</span>',lead:'Skupione środowisko dla kalkulatorów, procesów staffingowych, narzędzi workforce i prywatnych projektów. Narzędzia są schowane, dopóki ich nie potrzebujesz.',launchTools:'Otwórz narzędzia',heroNote:'17 pozycji · PL / EN / NL · chroniony workspace',system:'SYSTEM',ready:'GOTOWY',interface:'INTERFEJS',access:'DOSTĘP',principleKicker:'ZAPROJEKTOWANE WOKÓŁ PRACY',principleTitle:'Jeden spokojny interfejs. Każde narzędzie o jedno polecenie dalej.',principleCopy:'Strona jest warstwą sterującą, a nie katalogiem. Kalkulatory i moduły operacyjne pozostają schowane w przeszukiwalnym launcherze i otwierają się w czystym workspace z zachowaniem własnego interfejsu.',cap1:'Stawki i finanse',cap1c:'Budżet, bill rate, merit i kalkulacje CAO.',cap2:'Staffing i rekrutacja',cap2c:'Intake, CV matching i workflow dostawców.',cap3:'Workforce operations',cap3c:'Spotkania, home office i rejestry operacyjne.',cap4:'Prywatny workspace',cap4c:'Chronione projekty i lokalny asystent AI.',command:'COMMAND CENTER',calloutTitle:'Znajdź narzędzie. Otwórz je. Wracaj do pracy.',browseTools:'Pokaż wszystkie narzędzia',footer:'BUSINESS TOOLS / AUTOMATION / AI',launcherLabel:'TOOL LAUNCHER',launcherTitle:'Czego potrzebujesz?',search:'Szukaj narzędzia, kalkulacji lub procesu…',selectHint:'ENTER ABY OTWORZYĆ',noResults:'Brak pasujących narzędzi.',back:'Powrót',loaded:'GOTOWE',loading:'Otwieram narzędzie…',protected:'CHRONIONY DOSTĘP',pinTitle:'Wpisz kod dostępu',cancel:'Anuluj',continue:'Dalej',wrongPin:'Nieprawidłowy kod.',aiIntro:'Zapytaj o platformę albo powiedz, które narzędzie mam otworzyć. Klucz API nie jest potrzebny.',aiPlaceholder:'Zapytaj o platformę…',aiNote:'KOMENDY STRONY DZIAŁAJĄ LOKALNIE · GENERAL AI JEST OPCJONALNE',all:'Wszystkie',finance:'Stawki i finanse',staffing:'Staffing i rekrutacja',workforce:'Workforce',private:'Prywatne',results:'narzędzi'},
en:{navAbout:'Platform',navAi:'AI Assistant',openTools:'Open tools',eyebrow:'BUSINESS OPERATING LAYER',headline:'Work tools.<br><span>Without the clutter.</span>',lead:'A focused workspace for calculators, staffing workflows, workforce utilities and private projects. Tools stay out of the way until you need them.',launchTools:'Launch tools',heroNote:'17 entries · PL / EN / NL · protected workspace',system:'SYSTEM',ready:'READY',interface:'INTERFACE',access:'ACCESS',principleKicker:'DESIGNED AROUND THE WORK',principleTitle:'One calm interface. Every tool one command away.',principleCopy:'The website is the control layer, not a catalogue. Calculators and operational modules remain hidden inside a searchable launcher and open in a distraction-free workspace with their original interface intact.',cap1:'Rates & finance',cap1c:'Budget, bill rate, merit and CAO calculations.',cap2:'Staffing & recruitment',cap2c:'Intake, CV matching and supplier workflows.',cap3:'Workforce operations',cap3c:'Meetings, home office and operational registers.',cap4:'Private workspace',cap4c:'Protected projects and local AI assistance.',command:'COMMAND CENTER',calloutTitle:'Find the tool. Open it. Get back to work.',browseTools:'Browse all tools',footer:'BUSINESS TOOLS / AUTOMATION / AI',launcherLabel:'TOOL LAUNCHER',launcherTitle:'What do you need?',search:'Search tools, calculations or workflows…',selectHint:'ENTER TO OPEN',noResults:'No matching tools.',back:'Back',loaded:'LOADED',loading:'Opening tool…',protected:'PROTECTED ACCESS',pinTitle:'Enter access code',cancel:'Cancel',continue:'Continue',wrongPin:'Incorrect code.',aiIntro:'Ask about the platform or tell me which tool you want to open. No API key is required.',aiPlaceholder:'Ask about the platform…',aiNote:'SITE COMMANDS RUN LOCALLY · GENERAL AI IS OPTIONAL',all:'All tools',finance:'Rates & finance',staffing:'Staffing & recruitment',workforce:'Workforce',private:'Private',results:'tools'},
nl:{navAbout:'Platform',navAi:'AI Assistant',openTools:'Tools',eyebrow:'BUSINESS OPERATING LAYER',headline:'Tools voor werk.<br><span>Zonder rommel.</span>',lead:'Een gerichte workspace voor calculators, staffingworkflows, workforce-tools en privéprojecten. Tools blijven uit beeld totdat je ze nodig hebt.',launchTools:'Open tools',heroNote:'17 items · PL / EN / NL · beveiligde workspace',system:'SYSTEEM',ready:'GEREED',interface:'INTERFACE',access:'TOEGANG',principleKicker:'ONTWORPEN ROND HET WERK',principleTitle:'Eén rustige interface. Elke tool één opdracht verwijderd.',principleCopy:'De website is de besturingslaag, geen catalogus. Calculators en operationele modules blijven verborgen in een doorzoekbare launcher en openen in een rustige workspace met hun oorspronkelijke interface intact.',cap1:'Tarieven & finance',cap1c:'Budget, bill rate, merit en CAO-berekeningen.',cap2:'Staffing & recruitment',cap2c:'Intake, CV matching en supplier-workflows.',cap3:'Workforce operations',cap3c:'Meetings, home office en operationele registers.',cap4:'Privé workspace',cap4c:'Beveiligde projecten en lokale AI-assistent.',command:'COMMAND CENTER',calloutTitle:'Vind de tool. Open hem. Ga verder met je werk.',browseTools:'Bekijk alle tools',footer:'BUSINESS TOOLS / AUTOMATION / AI',launcherLabel:'TOOL LAUNCHER',launcherTitle:'Wat heb je nodig?',search:'Zoek tools, berekeningen of workflows…',selectHint:'ENTER OM TE OPENEN',noResults:'Geen passende tools.',back:'Terug',loaded:'GELADEN',loading:'Tool openen…',protected:'BEVEILIGDE TOEGANG',pinTitle:'Voer toegangscode in',cancel:'Annuleren',continue:'Doorgaan',wrongPin:'Onjuiste code.',aiIntro:'Vraag iets over het platform of zeg welke tool je wilt openen. Er is geen API-sleutel nodig.',aiPlaceholder:'Vraag iets over het platform…',aiNote:'SITE-COMMANDO’S DRAAIEN LOKAAL · ALGEMENE AI IS OPTIONEEL',all:'Alle tools',finance:'Tarieven & finance',staffing:'Staffing & recruitment',workforce:'Workforce',private:'Privé',results:'tools'}
};
let lang=normalizeLang(localStorage.getItem('rw_lang')||'pl');
let activeCategory='all',query='',selectedIndex=0,filteredTools=[...TOOLS],pendingTool=null,activeTool=null;
function normalizeLang(v){v=String(v||'').slice(0,2).toLowerCase();return ['pl','en','nl'].includes(v)?v:'pl'}
function tr(k){return I18N[lang]?.[k]||I18N.en[k]||k}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function categoryLabel(k){return tr(k)}
function setLang(v){lang=normalizeLang(v);localStorage.setItem('rw_lang',lang);localStorage.setItem('doc_lang',lang);localStorage.setItem('supplier_lang',lang);renderLanguage();renderFilters();renderTools();syncActiveLanguage()}
function renderLanguage(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(el=>{const v=tr(el.dataset.i18n);if(v)el.textContent=v});$$('[data-i18n-html]').forEach(el=>{const v=tr(el.dataset.i18nHtml);if(v)el.innerHTML=v});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=tr(el.dataset.i18nPlaceholder));$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang))}
function renderFilters(){const wrap=$('#toolFilters');if(!wrap)return;wrap.innerHTML=CATEGORIES.map(c=>{const count=c==='all'?TOOLS.length:TOOLS.filter(t=>t.category===c).length;return `<button class="filter-button ${c===activeCategory?'active':''}" type="button" data-filter="${c}"><span>${esc(categoryLabel(c))}</span><span>${count}</span></button>`}).join('');$$('[data-filter]',wrap).forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.filter;selectedIndex=0;renderFilters();renderTools()}))}
function normalized(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function renderTools(){const q=normalized(query).trim();filteredTools=TOOLS.filter(t=>(activeCategory==='all'||t.category===activeCategory)&&(!q||normalized(`${t.name} ${t.desc} ${t.keywords}`).includes(q)));if(selectedIndex>=filteredTools.length)selectedIndex=Math.max(0,filteredTools.length-1);$('#resultsCount').textContent=`${filteredTools.length} ${tr('results')}`;$('#emptyState').hidden=filteredTools.length>0;const list=$('#toolList');list.innerHTML=filteredTools.map((t,i)=>`<button class="tool-row ${i===selectedIndex?'selected':''}" type="button" role="option" aria-selected="${i===selectedIndex}" data-tool="${t.id}"><span class="tool-abbr">${esc(t.abbr)}</span><span class="tool-copy"><strong>${esc(t.name)}</strong><small>${esc(t.desc)}</small></span><span class="tool-category">${esc(categoryLabel(t.category))}</span><span class="tool-arrow">→</span></button>`).join('');$$('[data-tool]',list).forEach((row,i)=>{row.addEventListener('mouseenter',()=>{selectedIndex=i;updateSelection()});row.addEventListener('click',()=>requestOpen(TOOLS.find(t=>t.id===row.dataset.tool)))})}
function updateSelection(){$$('.tool-row').forEach((r,i)=>{r.classList.toggle('selected',i===selectedIndex);r.setAttribute('aria-selected',String(i===selectedIndex))});$('.tool-row.selected')?.scrollIntoView({block:'nearest'})}
function openPalette(){const p=$('#toolPalette'),b=$('#paletteBackdrop');p.hidden=false;b.hidden=false;document.body.style.overflow='hidden';query='';activeCategory='all';selectedIndex=0;$('#toolSearch').value='';renderFilters();renderTools();setTimeout(()=>$('#toolSearch').focus(),50)}
function closePalette(){if($('#toolPalette').hidden)return;$('#toolPalette').hidden=true;$('#paletteBackdrop').hidden=true;if($('#workspace').hidden&&$('#aiPanel').hidden)document.body.style.overflow='';}
function requestOpen(tool){if(!tool)return;closePalette();pendingTool=tool;const gate=$('#pinGate');$('#pinTool').textContent=tool.name;$('#pinInput').value='';$('#pinInput').maxLength=(tool.pin||DEFAULT_PIN).length;$('#pinError').textContent='';gate.hidden=false;setTimeout(()=>$('#pinInput').focus(),20)}
function cancelPin(){$('#pinGate').hidden=true;pendingTool=null}
function submitPin(){if(!pendingTool)return;const expected=pendingTool.pin||DEFAULT_PIN;if($('#pinInput').value!==expected){$('#pinError').textContent=tr('wrongPin');$('#pinInput').value='';$('#pinInput').focus();return}const tool=pendingTool;pendingTool=null;$('#pinGate').hidden=true;openTool(tool)}
function openTool(tool){if(tool.type==='download'){const a=document.createElement('a');a.href=tool.src;a.download='Merit_2026_Employee_Bulk_Calculator_350_exact.xlsx';document.body.appendChild(a);a.click();a.remove();return}activeTool=tool;try{localStorage.setItem('rw_active_v2_tool',tool.id)}catch{};$('#workspaceTitle').textContent=tool.name;$('#workspaceCategory').textContent=categoryLabel(tool.category).toUpperCase();$('#workspace').hidden=false;document.body.style.overflow='hidden';const loading=$('#moduleLoading');loading.classList.remove('done');loading.querySelector('p').textContent=tr('loading');const frame=$('#moduleFrame');frame.removeAttribute('srcdoc');frame.src='about:blank';setTimeout(()=>{frame.src=tool.type==='legacy'?`./legacy-bridge.html?idx=${tool.idx}&lang=${lang}`:tool.src},0)}
function closeWorkspace(){activeTool=null;$('#workspace').hidden=true;$('#moduleFrame').src='about:blank';document.body.style.overflow='';try{localStorage.removeItem('rw_active_v2_tool')}catch{}}
function markLoaded(){setTimeout(()=>$('#moduleLoading').classList.add('done'),80)}
function syncActiveLanguage(){const frame=$('#moduleFrame');if(!activeTool||!frame)return;try{frame.contentWindow?.postMessage({type:'rw:setLang',lang},'*')}catch{};try{const w=frame.contentWindow;w?.localStorage?.setItem('rw_lang',lang);w?.localStorage?.setItem('doc_lang',lang)}catch{};$('#workspaceCategory').textContent=categoryLabel(activeTool.category).toUpperCase()}
function openAi(){closePalette();$('#aiPanel').hidden=false;$('#aiBackdrop').hidden=false;document.body.style.overflow='hidden';if(!$('#aiLog').children.length)addAi('assistant',tr('aiIntro'));setTimeout(()=>$('#aiInput').focus(),40)}
function closeAi(){$('#aiPanel').hidden=true;$('#aiBackdrop').hidden=true;if($('#workspace').hidden)document.body.style.overflow=''}
function addAi(role,text){const m=document.createElement('div');m.className=`ai-message ${role}`;m.textContent=text;$('#aiLog').appendChild(m);$('#aiLog').scrollTop=$('#aiLog').scrollHeight}
function matchTool(text){const q=normalized(text);let best=null,score=0;for(const t of TOOLS){const name=normalized(t.name),tokens=normalized(`${t.name} ${t.keywords}`).split(/\s+/).filter(x=>x.length>2);let s=name&&q.includes(name)?20:0;tokens.forEach(x=>{if(q.includes(x))s++});if(s>score){score=s;best=t}}return score>=2?best:null}
function aiReply(text){const q=normalized(text);const tool=matchTool(text);if(tool&&(q.includes('otw')||q.includes('open')||q.includes('uruch')||q.includes('start')||q.includes('toon')||q.includes('openen'))){addAi('assistant',`${lang==='pl'?'Otwieram':lang==='nl'?'Ik open':'Opening'}: ${tool.name}`);setTimeout(()=>{closeAi();requestOpen(tool)},350);return}if(q.includes('jakie')||q.includes('which')||q.includes('welke')||q.includes('narzed')||q.includes('tools')){addAi('assistant',TOOLS.map(t=>t.name).join(' · '));return}if(q.includes('pin')||q.includes('kod')||q.includes('code')){addAi('assistant',lang==='pl'?'Dostęp do narzędzi jest chroniony istniejącym mechanizmem PIN. Kod wpisujesz dopiero przy otwieraniu narzędzia.':lang==='nl'?'Tools zijn beschermd met de bestaande PIN-toegang. Je voert de code pas in wanneer je een tool opent.':'Tools use the existing PIN access. You enter the code only when opening a tool.');return}if(tool){addAi('assistant',`${tool.name} — ${tool.desc}`);return}addAi('assistant',lang==='pl'?'Mogę bez klucza API obsługiwać platformę, wyszukiwać i otwierać jej narzędzia. Pełny model do pytań ogólnych będzie uruchamiany lokalnie jako osobna warstwa, tak aby nie wysyłać klucza API do przeglądarki.':lang==='nl'?'Zonder API-sleutel kan ik het platform bedienen en tools zoeken en openen. Een volledig algemeen model kan als aparte lokale laag in de browser worden geladen.':'Without an API key I can operate the platform and find or open its tools. A full general model can be loaded as a separate local browser layer.');}
function sendAi(){const input=$('#aiInput'),text=input.value.trim();if(!text)return;input.value='';addAi('user',text);setTimeout(()=>aiReply(text),120)}
function bind(){
  $('#openTools').addEventListener('click',openPalette);$('#heroTools').addEventListener('click',openPalette);$('#bottomTools').addEventListener('click',openPalette);$('#closeTools').addEventListener('click',closePalette);$('#paletteBackdrop').addEventListener('click',closePalette);
  $('#toolSearch').addEventListener('input',e=>{query=e.target.value;selectedIndex=0;renderTools()});$('#toolSearch').addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();selectedIndex=Math.min(selectedIndex+1,filteredTools.length-1);updateSelection()}else if(e.key==='ArrowUp'){e.preventDefault();selectedIndex=Math.max(0,selectedIndex-1);updateSelection()}else if(e.key==='Enter'&&filteredTools[selectedIndex]){e.preventDefault();requestOpen(filteredTools[selectedIndex])}});
  $$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
  $('#pinCancel').addEventListener('click',cancelPin);$('#pinSubmit').addEventListener('click',submitPin);$('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')submitPin();if(e.key==='Escape')cancelPin()});$('#pinInput').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,e.target.maxLength)});
  $('#workspaceBack').addEventListener('click',closeWorkspace);$('#moduleFrame').addEventListener('load',()=>{if(activeTool?.type==='direct')markLoaded();syncActiveLanguage()});window.addEventListener('message',e=>{if(e.source===$('#moduleFrame').contentWindow&&e.data?.type==='rw:legacy-status'){if(e.data.ok)markLoaded();else{const p=$('#moduleLoading p');p.textContent=e.data.detail||'Unable to open tool.'}}});
  $('#openAi').addEventListener('click',openAi);$('#closeAi').addEventListener('click',closeAi);$('#aiBackdrop').addEventListener('click',closeAi);$('#aiSend').addEventListener('click',sendAi);$('#aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAi()});
  document.addEventListener('keydown',e=>{const edit=e.target&&e.target.matches?.('input,textarea,select,[contenteditable=true]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette();return}if(e.key==='Escape'){if(!$('#pinGate').hidden)cancelPin();else if(!$('#aiPanel').hidden)closeAi();else if(!$('#toolPalette').hidden)closePalette();else if(!$('#workspace').hidden)closeWorkspace()}else if(!edit&&e.key==='/'&&$('#toolPalette').hidden){e.preventDefault();openPalette()}})
}
async function qaDirect(tool){return new Promise(resolve=>{const f=document.createElement('iframe');f.style.cssText='position:fixed;width:2px;height:2px;opacity:0;pointer-events:none;left:-10px;top:-10px';let done=false;const finish=(ok,detail)=>{if(done)return;done=true;f.remove();resolve({id:tool.id,name:tool.name,type:tool.type,ok,detail})};const timer=setTimeout(()=>finish(false,'iframe timeout'),10000);f.onload=()=>{clearTimeout(timer);try{const d=f.contentDocument;const text=(d?.body?.innerText||'').replace(/\s+/g,' ').trim();finish(text.length>10,`body:${text.length}`)}catch(e){finish(false,String(e?.message||e))}};document.body.appendChild(f);f.src=tool.src})}
async function qaLegacy(tool){return new Promise(resolve=>{const f=document.createElement('iframe');f.style.cssText='position:fixed;width:3px;height:3px;opacity:0;pointer-events:none;left:-20px;top:-20px';let done=false;const finish=(ok,detail)=>{if(done)return;done=true;window.removeEventListener('message',onMsg);f.remove();resolve({id:tool.id,name:tool.name,type:tool.type,ok,detail})};const onMsg=e=>{if(e.source===f.contentWindow&&e.data?.type==='rw:legacy-status'&&Number(e.data.idx)===tool.idx)finish(!!e.data.ok,e.data.detail||'')};window.addEventListener('message',onMsg);setTimeout(()=>finish(false,'legacy timeout'),18000);document.body.appendChild(f);f.src=`./legacy-bridge.html?idx=${tool.idx}&qa=1`})}
async function qaDownload(tool){try{const r=await fetch(tool.src,{cache:'no-store'});return{id:tool.id,name:tool.name,type:tool.type,ok:r.ok&&Number(r.headers.get('content-length')||1)>0,detail:`HTTP ${r.status}`}}catch(e){return{id:tool.id,name:tool.name,type:tool.type,ok:false,detail:String(e?.message||e)}}}
async function runAllQA(){const results=[];for(const tool of TOOLS){let r;if(tool.type==='legacy')r=await qaLegacy(tool);else if(tool.type==='download')r=await qaDownload(tool);else r=await qaDirect(tool);results.push(r);console.log('[RW QA]',r.ok?'PASS':'FAIL',tool.name,r.detail)}return{ok:results.every(r=>r.ok),count:results.length,passed:results.filter(r=>r.ok).length,failed:results.filter(r=>!r.ok).length,results}}
window.RWV2={tools:TOOLS,openTools:openPalette,openToolById:id=>requestOpen(TOOLS.find(t=>t.id===id)),setLang,getLang:()=>lang};
window.RWQA={runAll:runAllQA};
bind();renderLanguage();renderFilters();renderTools();
})();