(function(){
'use strict';
const EMAIL='rafalwilk.aitech@gmail.com';
const COPY={
  pl:{interfaceValue:'PLATFORMA WWW',accessValue:'BEZPIECZNY DOSTĘP',contactKicker:'KONTAKT',contactTitle:'Porozmawiajmy o AI, automatyzacji i praktycznych narzędziach.',contactCopy:'Rafal Wilk AI to niezależna platforma skupiona na praktycznych rozwiązaniach AI, automatyzacji procesów i narzędziach wspierających codzienną pracę biznesową.',contactLabel:'E-mail',footerAbout:'Praktyczne AI, automatyzacja i narzędzia biznesowe w jednym uporządkowanym środowisku.',footerNav:'Nawigacja',footerContact:'Kontakt',footerLegal:'Informacje prawne',linkPlatform:'Platforma',linkTools:'Narzędzia',linkAssistant:'AI Assistant',linkLegal:'Prywatność i informacje prawne',linkTerms:'Warunki korzystania',linkDisclaimer:'Zastrzeżenia',rights:'Wszelkie prawa zastrzeżone.',independent:'Niezależna strona internetowa. Nazwy i znaki podmiotów trzecich należą do ich właścicieli.'},
  en:{interfaceValue:'WEB PLATFORM',accessValue:'SECURE ACCESS',contactKicker:'CONTACT',contactTitle:'Let’s talk about AI, automation and practical tools.',contactCopy:'Rafal Wilk AI is an independent platform focused on practical AI solutions, process automation and tools that support everyday business work.',contactLabel:'Email',footerAbout:'Practical AI, automation and business tools in one focused workspace.',footerNav:'Navigation',footerContact:'Contact',footerLegal:'Legal',linkPlatform:'Platform',linkTools:'Tools',linkAssistant:'AI Assistant',linkLegal:'Privacy & legal information',linkTerms:'Terms of use',linkDisclaimer:'Disclaimer',rights:'All rights reserved.',independent:'Independent website. Third-party names and trademarks remain the property of their respective owners.'},
  nl:{interfaceValue:'WEBPLATFORM',accessValue:'BEVEILIGDE TOEGANG',contactKicker:'CONTACT',contactTitle:'Laten we praten over AI, automatisering en praktische tools.',contactCopy:'Rafal Wilk AI is een onafhankelijk platform gericht op praktische AI-oplossingen, procesautomatisering en tools voor dagelijks zakelijk werk.',contactLabel:'E-mail',footerAbout:'Praktische AI, automatisering en zakelijke tools in één overzichtelijke workspace.',footerNav:'Navigatie',footerContact:'Contact',footerLegal:'Juridisch',linkPlatform:'Platform',linkTools:'Tools',linkAssistant:'AI Assistant',linkLegal:'Privacy & juridische informatie',linkTerms:'Gebruiksvoorwaarden',linkDisclaimer:'Disclaimer',rights:'Alle rechten voorbehouden.',independent:'Onafhankelijke website. Namen en merken van derden blijven eigendom van hun respectieve eigenaren.'}
};
function lang(){const v=(document.documentElement.lang||localStorage.getItem('rw_lang')||'pl').slice(0,2).toLowerCase();return ['pl','en','nl'].includes(v)?v:'pl'}
function render(){const dict=COPY[lang()]||COPY.pl;document.querySelectorAll('[data-site-i18n]').forEach(el=>{const v=dict[el.dataset.siteI18n];if(v)el.textContent=v});document.querySelectorAll('[data-contact-email]').forEach(el=>{el.textContent=EMAIL;if(el.tagName==='A')el.href='mailto:'+EMAIL})}
function patchTools(){const tools=window.RWV2&&Array.isArray(window.RWV2.tools)?window.RWV2.tools:[];for(const tool of tools){if(tool.type==='legacy'){tool.type='direct';tool.src=`./legacy-module.html?idx=${tool.idx}&lang=${encodeURIComponent(lang())}`;tool.legacyDirect=true}if(tool.id==='projects'){tool.type='direct';tool.src='./my-projects-module.html';tool.projectsWrapped=true}}}
function refreshToolLang(){const tools=window.RWV2&&Array.isArray(window.RWV2.tools)?window.RWV2.tools:[];for(const tool of tools){if(tool.legacyDirect)tool.src=`./legacy-module.html?idx=${tool.idx}&lang=${encodeURIComponent(lang())}`}}
function bindSiteActions(){document.querySelectorAll('[data-open-tools]').forEach(el=>el.addEventListener('click',()=>window.RWV2&&window.RWV2.openTools()));document.querySelectorAll('[data-open-ai]').forEach(el=>el.addEventListener('click',()=>document.getElementById('openAi')?.click()));}
patchTools();render();bindSiteActions();
new MutationObserver(()=>{render();refreshToolLang()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
window.addEventListener('message',event=>{if(event.data&&event.data.type==='rw:module-error'){const loading=document.getElementById('moduleLoading');const p=loading&&loading.querySelector('p');if(loading)loading.classList.remove('done');if(p)p.textContent=event.data.detail||'Unable to open tool.';}});
})();